version: "2.2"

services:
    frontend:
        build: ./frontend
        ports:
            - 8000:8000
        volumes:
        - ./frontend:/frontend-code
        
    backend:
        build: ./backend
        ports:
            - 9000:9000
        volumes:
        - ./backend:/backend-code
        